name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # deploy on every push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npm install -g gh-pages
      - run: gh-pages -d build -b gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
